### PR TITLE
(geojson) fix: Do not add special keys to PropertyRecord

### LINKED ISSUE #104: (geojson) PropertyRecord class allows adding special properties on multiple methods
Methods like addProperty, addNumerical, createFromFeature, createFromJson all seem to allow that special properties are added to the record, while they should not be in the record.

### PR DESCRIPTION
**Pull request by wpmg**
- Fixes #104: It should not be possible to add special keys to PropertyRecord

### CODE REVIEW

File: packages/envisim-geojson/src/property-record.ts [hunk 1]
```diff
@@ -183,6 +197,8 @@ export class PropertyRecord<IDS extends string = string> {
     this: PropertyRecord<string>,
     { id = uuid(), name = id, parent }: Partial<NumericalProperty<string>>,
   ): string {
+    if (PropertyRecord.isSpecial(id)) throw new RangeError("cannot att special key to record");
```
Comment (AntonGrafstrom) [inline packages/envisim-geojson/src/property-record.ts:200]: att -> add

File: packages/envisim-geojson/src/property-record.ts [hunk 2]
```diff
@@ -201,6 +217,8 @@ export class PropertyRecord<IDS extends string = string> {
     this: PropertyRecord<string>,
     { id = uuid(), name = id, values = [] }: Partial<CategoricalProperty<string>>,
   ): string {
+    if (PropertyRecord.isSpecial(id)) throw new RangeError("cannot att special key to record");
```
Comment (AntonGrafstrom) [inline packages/envisim-geojson/src/property-record.ts:220]: att -> add

**Review by AntonGrafstrom — CHANGES_REQUESTED** [review]

**Comment by wpmg** [comment]
Fixed the spelling error(s)

**Review by AntonGrafstrom — APPROVED** [review]
